### ISSUE TITLE
Cleo crashes gta sa through half of the loading

### ISSUE THREAD

**Issue by imhavingdiahrreahelp** [cleolibrary/CLEO4#39]
for some reason CLEO4 just murders gta sa when its loading and i bassicly just got gta sa

 even tho I tried to do evreything it still crashed plz help

**Comment by eshelton98** [comment]
The exact same thing is happening to me and I have yet to find an answer that helps me.

**Comment by necggry** [comment]
same i wanted mysterix mod so bad but i literally gave up because after my 9549594th attempt cleo still crashed
for me it crashes whenever u load a save or create a new save

**Comment by necggry** [comment]
i actually managed to fix it later but idk if CLEO was even enabled because the mods didnt even load like they didnt exist

**Comment by imhavingdiahrreahelp** [comment]
try running it in compatibility mode in W95/ME And check run it 640 x
whatever

that should fix it.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by KAZOKU70** [comment]
> I had the same problem for some time and the only solution I had was to delete the CLEO saves ($GTASA_FOLDER\CLEO\cleo_saves*), the only drawback is that there may be problems with some mods that generate content that is recorded in save the game...
> 
> Another problem is that there may be some incompatible or damaged mod, in that case the game crashes because it tries to execute an unknown opcode or whose arguments are invalid... Try running the game without the cleo mods (.cs and .cs3 files) and see using them one by one until you find the problematic mod. It is a bit tedious but in order to correct any problem you must first arm yourself with a lot of patience
> 
> Cheers! ;D

i dont even have any cleo mods and its crashing

**Comment by Renso-Takahashi** [comment]
Hi!

First of all, try to install the Open Limit Adjuster mod if you don't
have it, one of the most common cases of crashing is due to the use of
mods that require a lot of streaming memory with the original limits
of the game

A clear example is the use of the Mods like FirstPerson, IMFX, the use
of heavy skins with the Skin Selector and even the use of HD textures
without having installed a mod that removes the memory limit such as
MixSets or Open Limit Adjuster or both

You should know that the StreamMemFix does not usually work, so if you
trust it then better remove it and install the MixSets or the Open
Limit Adjuster

The SilentPatchSA is also quite useful, if you combine it with the
MixSets and the Open Limit Adjuster your game would improve a lot

Cheers! =D
